# Production
# FROM node:16 AS build

# Development
FROM node:20

WORKDIR /app
COPY client/package.json client/package-lock.json ./

RUN npm install --legacy-peer-deps
RUN npm install --save-dev webpack webpack-cli

COPY client/ ./

EXPOSE 3000

# Development
CMD ["npm", "start"]

# Production
# RUN npm run build

# FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf 
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]